sudo: false

language: php

php:
  - '5.3'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  global:
    - WP_VERSION=latest


before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"


script:
  - WP_MULTISITE=0 phpunit
  - WP_MULTISITE=1 phpunit



cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache


notifications:
  email:
    on_success: never
    on_failure: change
